server:
  port: 8089

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: product-route
          uri: lb://productservice
          predicates:
            - Path=/productos/**

        - id: ordenes-route
          uri: lb://ordenservice
          predicates:
            - Path=/ordenes/**

        - id: pagos-route
          uri: lb://pagoservice
          predicates:
            - Path=/pagos/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/